@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "clean.code.practice_2.task_6",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "clean.code.practice_2.task_6.Main",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_3059181 { 
   	label=code
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_675255503 { 
   	label=practice_2
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   GUIFactory443260736[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)GUIFactory</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># createButton(): Button</TD></TR>
<TR><TD ALIGN="LEFT" ># createMenu(): Menu</TD></TR>
<TR><TD ALIGN="LEFT" ># createWindow(): Window</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

MacOSButton443260736[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MacOSButton</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ pushButton()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

MacOSGUIFactory443260736[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MacOSGUIFactory</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># createButton(): Button</TD></TR>
<TR><TD ALIGN="LEFT" ># createMenu(): Menu</TD></TR>
<TR><TD ALIGN="LEFT" ># createWindow(): Window</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

MacOSMenu443260736[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MacOSMenu</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ launchMenu()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

MacOSWindow443260736[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MacOSWindow</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ openWindow()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Main443260736[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Main</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># main(args: String[])</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

WindowsButton443260736[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)WindowsButton</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ pushButton()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

WindowsGUIFactory443260736[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)WindowsGUIFactory</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># createButton(): Button</TD></TR>
<TR><TD ALIGN="LEFT" ># createMenu(): Menu</TD></TR>
<TR><TD ALIGN="LEFT" ># createWindow(): Window</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

WindowsMenu443260736[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)WindowsMenu</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ launchMenu()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

WindowsWindow443260736[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)WindowsWindow</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ openWindow()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
GUIFactory443260736 -> MacOSGUIFactory443260736[arrowhead=none, arrowtail=empty, dir=both];
GUIFactory443260736 -> WindowsGUIFactory443260736[arrowhead=none, arrowtail=empty, dir=both];
Main443260736 -> MacOSButton443260736[arrowhead=none];
Main443260736 -> MacOSMenu443260736[arrowhead=none];
Main443260736 -> MacOSWindow443260736[arrowhead=none];
Main443260736 -> WindowsButton443260736[arrowhead=none];
Main443260736 -> WindowsMenu443260736[arrowhead=none];
Main443260736 -> WindowsWindow443260736[arrowhead=none];
    
}
@enduml